version: '3'
services:

  master:
    build: .
    container_name: master
    command: roscore
    network_mode: host

  caller:
    build: .
    container_name: caller
    environment:
      - "ROS_HOSTNAME=caller"
    command: bash -c "cd catkin_ws; catkin_make; source devel/setup.bash; rosrun khr_ros caller 1 3"
    network_mode: host

  server:
    build: .
    container_name: server
    environment:
      - "ROS_HOSTNAME=server"
    command: bash /ros_entrypoint.sh roslaunch khr_ros server
